### PR TITLE
Entities

### PR DESCRIPTION
**Pull request by jpmedinagl**
Completed all of the entities. 

Entities added:
- CourseFactory & Course
- PrerequisiteFactory & Prerequisite
- StudentFactory & Student
- QuestionFactory & Question

Test have not yet been added. Will be added later.

### CODE REVIEW

**Review by TheFaceOfKled — APPROVED** [review]
Nice use of overloading

**Comment by antsochia** [comment]
Outline of the code was good. The documents also made it easy to understand!

**Review by hassa963 — CHANGES_REQUESTED** [review]
can you make the map in student have the keys be the course id and then the value is the grade instead of saving the whole course?

**Review by hassa963 — APPROVED** [review]
Thank you for making the change.

**Comment by AdelinaPatlatii** [comment]
For now everything looks great!

**Review by AdelinaPatlatii — APPROVED** [review]

**Pull request merged**
